# Generated by Django 4.0.6 on 2024-12-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('key_skills', models.TextField()),
            ],
        ),
    ]
