# Generated by Django 4.0.6 on 2024-12-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0003_salarybycity_skill_remove_vacancy_key_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
